# kind-cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.31.4 # Use a specific Kubernetes version
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
  - role: worker
    image: kindest/node:v1.31.4
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: homelab-cluster-node-1
          kubeletExtraArgs:
            node-labels: "worker=node-1"
  - role: worker
    image: kindest/node:v1.31.4
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: homelab-cluster-node-2
          kubeletExtraArgs:
            node-labels: "worker=node-2"
  - role: worker
    image: kindest/node:v1.31.4
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: homelab-cluster-node-3
          kubeletExtraArgs:
            node-labels: "worker=node-3"
